### ISSUE TITLE
Spin template on Rouen case study did not compile anymore

### ISSUE THREAD

**Issue by chapuisk** [ANRGenstar/template#1]
See `src/main/java/rouen/spin/NetworkOnPopulation.java`

**Comment by benoitgaudou** [comment]
I am very sorry, but on my eclipse, the the NEtworkOnPopulation.java
compiles ... and GSCRouen.java has compilation error.

Benoit

2017-12-13 3:53 GMT+01:00 Kevin Chapuis <notifications@github.com>:
